config/routes.rb
Rails.application.routes.draw do
  resources :slides do
    collection do
      post 'cleanup'
    end
  end
  resources :decks do
      member do
          get 'display'
          get 'reorder'
      end
  end
  get 'utilities', to: 'welcome#utils', as: :utilities

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deck.rb
class Deck < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :decks_slides
    has_many :slides, through: :decks_slides

    def slide_urls
      decks_slides.order(:order).map{|ds| {duration: ds.slide.duration, url: ds.slide.attachment.url(:full)}}
    end
end

app/models/decks_slide.rb
class DecksSlide < ApplicationRecord
  belongs_to :deck
  belongs_to :slide
end

app/models/slide.rb
require 'exifr'

class Slide < ApplicationRecord
  has_attached_file :attachment, styles: {preview: '300x300>', full: '1280x720>'}#, processors: [:artist_watermark]
  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\z/     

  has_many :decks_slides, dependent: :destroy
  has_many :decks, through: :decks_slides

  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :display, :edit, :update, :destroy, :reorder]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  def display
    render layout: 'display'
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reorder
    i = 0
    q = ''
    @deck.decks_slides.to_a.shuffle.each do |ds|
      ds.order = i
      q += ds.inspect + "\n"
      ds.save
      i += 1
    end
    redirect_to @deck, notice: "Reordered slides"
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_deck
    @deck = Deck.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def deck_params
    params.require(:deck).permit(:name, slide_id: [])
  end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.order(:name)
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
    if !@slide.name || @slide.name.empty
      @slide.name = @slide.attachment_file_name
    end
    if !@slide.duration
      @slide.duration = 5
    end
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def cleanup
    Slide.where("created_at < ?", params[:limit]).each do |s|
      s.decks.clear
      s.delete
    end
    redirect_to root_url
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:name, :attachment, deck_ids: [])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
      @decks = Deck.all
  end

  def utils

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/decks/_form.html.erb
<%= simple_form_for(@deck) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/decks/_slides.html.erb
<div class="columns is-multiline">
<% deck.decks_slides.order(:order).each do |ds| %>
 <div class="column">
  <div class="card">
    <div class="card-image">
      <figure class="image">
        <%= image_tag ds.slide.attachment.url(:preview), class: 'preview' %>
      </figure>
    </div>
    <div class="card-content">
      [<%= ds.order %>] <%= ds.slide.name %> <br/> Uploaded at <%= ds.slide.created_at.strftime('%Y-%m-%d %H:%M:%S') %>
    </div>
    <div class="card-footer">
      <%= link_to 'Show', ds.slide, class: 'button card-footer-item is-info' %>
      <%= link_to 'Edit', edit_slide_path(ds.slide), class: 'button card-footer-item is-warning' %>
      <% if ds.slide.decks.count > 0 %>
        <%= link_to ds.slide.decks.count, '#', class: 'button card-footer-item is-danger is-disabled' %>
      <% else %>
	<%= link_to 'Destroy', ds.slide, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button card-footer-item is-danger' %>
      <% end %>
    </div>
  </div>
 </div>
<% end %>
</div>

app/views/decks/display.html.erb
<div id="slider" style="position: absolute;">
  <img id="i" />
</div>

<script type="text/javascript">

var deck = null;
var index = 0;

$(function() {
    $.getJSON('<%= deck_path(@deck, format: 'json') %>', function(data) {
        deck = data;
	index = 0;
        $('#i').attr('src', deck.slide_urls[index].url);
	setTimeout(next, deck.slide_urls[index].duration* 1000);
    });
});

function getUpdate() {
    $.getJSON('<%= deck_path(@deck, format: 'json') %>', function(data) {
        deck = data;
    });
}

function next() {
    if(deck && deck.slide_urls.length > 1) {
        console.log('Has more than 1 image');
        pos = index;
        if(pos < 0) {
            pos = -1;
        }
        pos += 1;
        if(pos == deck.slide_urls.length) {
            console.log('Starting over at beginning');
            pos = 0;
        } else {
            console.log('Going to ' + pos);
        }
        $('#slider').append('<img id="j" src="' + deck.slide_urls[pos].url + '" />').animate({top: '-=720px'}, 0, function() {
            $('#i').attr('src', deck.slide_urls[pos].url);
            $('#slider').animate({top: '+=720px'}, 0, function() {
                $('#j').remove();
		setTimeout(next, deck.slide_urls[pos].duration* 1000);
		console.log('Next slide in ' + deck.slide_urls[pos].duration);
		index = pos;
            });
        });
    }
}

setInterval(getUpdate, 1000 * 60 * 2.5);


</script>

app/views/decks/edit.html.erb
<h1>Editing Deck</h1>

<%= render 'form', deck: @deck %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<h1>Slide Decks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Associated Slides</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.name %></td>
        <td>(<%= deck.slides.count %>)</td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slide Deck', new_deck_path, class: 'button is-dark is-large' %>

app/views/decks/new.html.erb
<h1>New Deck</h1>

<%= render 'form', deck: @deck %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<h1><%= @deck.name %></h1>

<h3>Slides</h3>

<br>

<%= render partial: 'slides', locals: {deck: @deck} %>


<%= link_to 'Reorder Slides', reorder_deck_path(@deck) %> |
<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>

<% content_for :sidebar do %>
<h4>Upload Images</h4>
<%= form_for(Slide.new, html: { id: 'slide-drop', multipart: true, class: 'dropzone'}) do |f|  %>
<input type="hidden" name="slide[deck_ids][]" value="<%= @deck.id %>" />
  <div class="fallback">
    <%= f.file_field :attachment %><br>
    <%= f.submit "Upload" %>
  </div>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotonWall</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <section class="hero is-small is-dark is-bold">
      <div class="hero-body">
        <div class="container">
	  <h1 class="title">PhotonWall</h1>
	</div>
      </div>
    </section>
    <br/>
    <div class="container">
      <div class="columns">
        <div class="column is-2">
	  <div class="box">
  	    <aside class="menu">
     	      <ul class="menu-item">
                <li><%= link_to "#{icon('tv', class: 'fa-fw')} Start Shows".html_safe, root_path %></li>
                <li><%= link_to "#{icon('list-alt', class: 'fa-fw')} Slide Decks".html_safe, decks_path %></li>
                <li><%= link_to "#{icon('tablet', class: 'fa-fw')} Slides".html_safe, slides_path %></li>
                <li><%= link_to "#{icon('gears', class: 'fa-fw')} Utilities".html_safe, utilities_path %></li>
	      </ul>
	    </aside>
	  </div>
	  <% if content_for?(:sidebar) %>
	  <div class="box">
	  <div class="content">
	    <%= content_for :sidebar %>
	    </div>
	  </div>
	  <% end %>
	</div>
	<div class="column">
	  <div class="content">
          <%= yield %>
          <% flash.each do |typ, msg| %>
            <div class="alert"><%= msg %></div>
          <% end %>
	  </div>
	  </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/display.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotonWall</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'display', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'display', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="display">
    <%= yield %>
  </body>
</html>

app/views/slides/_form.html.erb
<%= simple_form_for(@slide) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :attachment %>
    <%= f.input :deck_ids, collection: Deck.all, as: :check_boxes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/slides/_list.html.erb
<div class="columns is-multiline">
<% collection.each do |slide| %>
 <div class="column">
  <div class="card">
    <div class="card-image">
      <figure class="image">
        <%= image_tag slide.attachment.url(:preview), class: 'preview' %>
      </figure>
    </div>
    <div class="card-content">
      <%= slide.name %> <br/> <%= slide.strftime('%Y-%m-%d %H:%M:%S') %>
    </div>
    <div class="card-footer">
      <%= link_to 'Show', slide, class: 'button card-footer-item is-info' %>
      <%= link_to 'Edit', edit_slide_path(slide), class: 'button card-footer-item is-warning' %>
      <% if slide.decks.count > 0 %>
        <%= link_to slide.decks.count, '#', class: 'button card-footer-item is-danger is-disabled' %>
      <% else %>
	<%= link_to 'Destroy', slide, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button card-footer-item is-danger' %>
      <% end %>
    </div>
  </div>
 </div>
<% end %>
</div>

app/views/slides/edit.html.erb
<h1>Editing Slide</h1>

<%= render 'form', slide: @slide %>

<%= link_to 'Show', @slide %> |
	<%= link_to 'Delete', @slide, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button card-footer-item is-danger' %> |
<%= link_to 'Back', slides_path %>

app/views/slides/index.html.erb
<h1>Slides</h1>

<%= render partial: 'list', locals: {collection: @slides} %>
<br>

<% content_for :sidebar do %>
<!--
<h4>Upload Images</h4>
<%= form_for(Slide.new, html: { id: 'slide-drop', multipart: true, class: 'dropzone'}) do |f|  %>
<%= collection_check_boxes :slide, :deck_ids, Deck.all, :id, :name %>
  <div class="fallback">
    <%= f.file_field :attachment %><br>
    <%= f.submit "Upload" %>
  </div>
<% end %>
-->
<% end %>

app/views/slides/new.html.erb
<h1>New Slide</h1>

<%= render 'form', slide: @slide %>

<%= link_to 'Back', slides_path %>

app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slide.name %>
</p>

<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>

app/views/welcome/index.html.erb
<div class="tile is-ancestor">
<% @decks.each do |deck| %>
  <div class="tile is-4 box">
  <%= link_to deck.name, display_deck_path(deck), class: 'btn' %>
  </div>
<% end %>
</div>

app/views/welcome/utils.html.erb
<div class="tile">
  <div class="tile is-4 box">
    <h3>Delete Images Before Date</h3>
    <%= form_tag cleanup_slides_url do %>
      <%= text_field_tag :limit, nil, placeholder: 'YYYY-MM-DD HH:MM' %>
      <%= submit_tag 'Remove Images' %>
    <% end %>
  </div>
</div>